---
- name: Download & extract latest SonarQube
  hosts: 127.0.0.1
  become: yes
  tasks:


     - name: Rename latest SonarQube directory
       command: mv {{ item }} /opt/sonarqube/sonarqube-{{ new_version }}
       with_fileglob:
         - "/opt/sonarqube/sonarqube-{{ new_version }}.*"

